server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # Microservicio Incidencias (puerto 8083): expone reportes, detalles y tipos.
            - id: incidencias-service
              uri: http://127.0.0.1:8083
              predicates:
                - Path=/api/v1/incidencias/**,/api/v1/incidencia/**,/api/v1/tipo_incidencias/**

            # Microservicio Residencias (puerto 8082): expone regiones, comunas y residencias.
            - id: residencia-service
              uri: http://127.0.0.1:8082
              predicates:
                - Path=/api/v1/residencia/**

            - id: comuna-service
              uri: http://127.0.0.1:8082
              predicates:
                - Path=/api/v1/comuna/**

            - id: region-service
              uri: http://127.0.0.1:8082
              predicates:
                - Path=/api/v1/region/**

            - id: residencias-service
              uri: http://127.0.0.1:8082
              predicates:
                - Path=/api/v1/residencias/**