server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: incidencias-service
              uri: lb://incidencias
              predicates:
                - Path=/api/v1/incidencias/**,/api/v1/incidencia/**,/api/v1/tipo_incidencias/**,/incidencias/api-docs/**

            - id: espacios-service
              uri: lb://Espacios
              predicates:
                - Path=/api/v1/espacio/**,/api/v1/espacios/**,/api/v1/user/**,/espacios/api-docs/**

            - id: residencia-service
              uri: lb://Residencias
              predicates:
                - Path=/api/v1/residencia/**,/api/v1/comuna/**,/api/v1/region/**,/api/v1/residencias/**,/api/v2/residencia/**,/api/v2/comuna/**,/api/v2/region/**,/api/v2/residencias/**,/residencias/api-docs/**

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: Microservicio Residencias
        url: /residencias/api-docs
      - name: Microservicio Incidencias
        url: /incidencias/api-docs
        
      - name: Microservicio Espacios
        url: /espacios/api-docs
  api-docs:
    enabled: true